import { mkdir, writeFile } from 'node:fs/promises';
import { FACTORS, PLANS, MODEL_ID } from '../src/contract.mjs';
const root = new URL('../', import.meta.url);
async function put(path, data) { const url = new URL(path, root); await mkdir(new URL('./', url), {recursive:true}); await writeFile(url, typeof data === 'string' ? data : JSON.stringify(data, null, 2) + '\n'); }
const nullableNumber = { type:'number', nullable:true };
const timestamp = { type:'string', format:'date-time', nullable:true };
const factor = { type:'object', required:['score','weight','source_as_of','freshness'], properties:{score:{...nullableNumber,minimum:0,maximum:100},weight:{type:'number',minimum:0,maximum:1},coverage:nullableNumber,confidence:nullableNumber,source_as_of:timestamp,source_as_of_raw:{type:'string',nullable:true,description:'Original producer timestamp. Without an explicit timezone, normalized time stays null and freshness is unknown.'},label:{type:'string',nullable:true},details:{type:'string',nullable:true},notes:{type:'array',nullable:true,items:{type:'string'},description:'Producer notes, including fallback and stale-input warnings.'},freshness:{type:'string',enum:['fresh','stale','unknown']}} };
const record = { type:'object', required:['pair','score','model_id','model_version','collected_at','source_as_of','factors','freshness','observation_id'], properties:{
  pair:{type:'string'}, score:{...nullableNumber,minimum:1,maximum:100}, model_id:{type:'string',enum:[MODEL_ID]},model_version:{type:'string',nullable:true},
  model_identity_status:{type:'string',enum:['configured_producer_version','unversioned_upstream']},schema_version:{type:'string'},
  collected_at:timestamp, source_as_of:timestamp, upstream_timestamp:{...timestamp,description:'Timestamp reported by the producer. It is not represented as a verified computation or market quote time.'},
  freshness:{type:'string',enum:['fresh','stale','unknown']},factors:{type:'object',required:FACTORS,properties:Object.fromEntries(FACTORS.map(name=>[name,factor]))},
  missing_factors:{type:'array',items:{type:'string',enum:FACTORS}},confidence:nullableNumber,coverage:nullableNumber,observation_id:{type:'string'},methodology_url:{type:'string',format:'uri'}
}};
const err = {description:'Error response; unavailable scores are never fabricated.',content:{'application/json':{schema:{type:'object',required:['error','message'],properties:{error:{type:'string'},message:{type:'string'}}}}}};
const response = {description:'Observed IQ records. Billing counts non-null score records returned. History dates use collected_at; truncated responses contain the newest records in the window.',headers:{'X-RapidAPI-Billing':{schema:{type:'string'},description:'Provider response: Records=N. Configure a hard custom Records quota in RapidAPI.'}},content:{'application/json':{schema:{type:'object',required:['data','records_billed'],properties:{data:{type:'array',items:{$ref:'#/components/schemas/IqObservation'}},records_billed:{type:'integer'},truncated:{type:'boolean'},unavailable_pairs:{type:'array',items:{type:'string'}},source_warning:{type:'string',nullable:true},change:{type:'object',properties:{score_delta:nullableNumber,reason:{type:'string'}}}}}}}};
const pathPair = {name:'pair',in:'path',required:true,schema:{type:'string',enum:['BTCUSDT','ETHUSDT','SOLUSDT']}};
const routes = [
  ['/v1/iq','getIqBatch','Retrieve bounded Vi IQ observations',[{name:'pairs',in:'query',schema:{type:'string',default:'BTCUSDT'},description:'Comma-separated pairs from metadata. BASIC:1, PRO:3, ULTRA:25 maximum.'}]],
  ['/v1/iq/{pair}','getIq','Retrieve a Vi IQ score and six factors',[pathPair]],
  ['/v1/iq/{pair}/history','getIqHistory','Read retained observations (ULTRA)',[pathPair,{name:'from',in:'query',schema:{type:'string',format:'date-time'}},{name:'to',in:'query',schema:{type:'string',format:'date-time'}},{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:1000,default:1000}}]],
  ['/v1/iq/{pair}/changes','getIqChanges','Compare observed endpoints of one producer version (ULTRA)',[pathPair,{name:'from',in:'query',schema:{type:'string',format:'date-time'}},{name:'to',in:'query',schema:{type:'string',format:'date-time'}}]],
];
const spec = {openapi:'3.0.3',info:{title:'Vi IQ by Vultax — Crypto Market Quality API',version:'0.1.0',description:'Gateway implementation and launch package. Production marketplace access is pending publisher setup and the dedicated IQ reader connection. Scores are source-reported proprietary metrics, not forecasts. See metadata for actual coverage and timestamps.',contact:{name:'Vultax',url:'https://vultax.com'}},servers:[{url:process.env.PUBLIC_BASE_URL || 'http://127.0.0.1:3189',description:'Local gateway; replace with the verified deployed HTTPS URL when publishing.'}],security:[{BearerAuth:[]}],paths:Object.fromEntries(routes.map(([path,id,summary,parameters])=>[path,{get:{operationId:id,summary,parameters,responses:{200:response,...Object.fromEntries([400,401,403,429,500,503].map(code=>[code,err]))}}}])),components:{securitySchemes:{BearerAuth:{type:'http',scheme:'bearer'}},schemas:{IqObservation:record}}};
if (process.env.PUBLIC_BASE_URL) {
  spec.servers[0].description = 'Vi IQ gateway; authenticated data access, public coverage metadata.';
  spec.info.description = 'Read-only Vi IQ crypto observations with six factors, source timestamps, coverage and producer fallback notes. A consumer key or marketplace subscription is required for IQ data. Source-reported indicators are not forecasts; metadata reports actual observed history and model-version availability.';
  spec.info.contact.email = 'support@vultax.com';
}
spec.paths['/v1/metadata']={get:{operationId:'getMetadata',summary:'Get supported pairs, source configuration and observed history coverage',security:[],responses:{200:{description:'Current service metadata',content:{'application/json':{schema:{type:'object'}}}}}}};
await put('openapi.json',spec);
const rapid = structuredClone(spec); rapid.security=[{RapidApiKey:[]}]; rapid.components.securitySchemes={RapidApiKey:{type:'apiKey',in:'header',name:'X-RapidAPI-Key'}};
await put('integrations/rapidapi/openapi.json',rapid); await put('integrations/rapidapi/plans.json',{currency:'USD',status:'launch_configuration_not_activated',customQuota:'Records',quotaMode:'hard',plans:PLANS});
const collection={info:{name:'Vi IQ by Vultax',schema:'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',description:spec.info.description+'\n\nStart the local gateway with npm start. Set apiToken in a private environment, never publish a token. Production URLs will be added only after verification. Vultax: https://vultax.com/methodology'},variable:[{key:'baseUrl',value:spec.servers[0].url},{key:'pair',value:'BTCUSDT'}],auth:{type:'bearer',bearer:[{key:'token',value:'{{apiToken}}',type:'string'}]},item:[{name:'Coverage and methodology (no key)',request:{method:'GET',auth:{type:'noauth'},url:'{{baseUrl}}/v1/metadata'}},...routes.map(([path,,name])=>({name,request:{method:'GET',url:'{{baseUrl}}'+path.replace('{pair}','{{pair}}'),header:[{key:'Accept',value:'application/json'}]},event:[{listen:'test',script:{type:'text/javascript',exec:["pm.test('Response is JSON', () => pm.response.to.be.json);","if (pm.response.code === 200) { const b = pm.response.json(); pm.test('Data and billing contract', () => { pm.expect(b.data).to.be.an('array'); pm.expect(b.records_billed).to.eql(b.data.filter(x => x.score !== null).length); }); }"]}}]}))]};
collection.info.name='Vultax — Public Research and Vi IQ Developer Preview';
collection.info.description='Public research discovery works now without a key. The Vi IQ gateway requests run against the local developer preview until production marketplace launch is verified. '+collection.info.description;
if (process.env.PUBLIC_BASE_URL) {
  collection.info.name = 'Vultax — Public Research and Vi IQ API';
  collection.info.description = 'The research feed and Vi IQ coverage metadata are public. IQ observations require a private consumer key or enabled marketplace subscription. Keep apiToken in a private environment. '+spec.info.description+' Methodology: https://vultax.com/methodology';
}
collection.item.unshift({name:'Public research feed — live, no key',request:{method:'GET',auth:{type:'noauth'},url:'https://vultax.com/feed.xml',description:'Published research articles from Vultax. Historical studies are not live IQ scores.'}});
await put('integrations/postman/collection.json',collection);
await put('integrations/postman/environment.json',{name:'Vi IQ — private token',values:[{key:'baseUrl',value:spec.servers[0].url,enabled:true},{key:'apiToken',value:'',type:'secret',enabled:true}],_postman_variable_scope:'environment'});
const workflow={name:'Screen Vi IQ observations with freshness and coverage filters',nodes:[
 {id:'note',name:'Setup and provenance',type:'n8n-nodes-base.stickyNote',typeVersion:1,position:[-100,-220],parameters:{width:680,height:180,content:'## Vi IQ by Vultax\nSet the deployed base URL in Fetch Vi IQ. Select a Header Auth credential: Authorization = Bearer YOUR_TOKEN. This workflow contains no secrets. Manual trigger only. Keep missing and stale observations visible. Methodology: https://vultax.com/methodology'}},
 {id:'manual',name:'Run screen',type:'n8n-nodes-base.manualTrigger',typeVersion:1,position:[0,40],parameters:{}},
 {id:'fetch',name:'Fetch Vi IQ',type:'n8n-nodes-base.httpRequest',typeVersion:4.2,position:[240,40],parameters:{url:'http://127.0.0.1:3189/v1/iq',authentication:'genericCredentialType',genericAuthType:'httpHeaderAuth',sendQuery:true,queryParameters:{parameters:[{name:'pairs',value:'BTCUSDT,ETHUSDT,SOLUSDT'}]},options:{timeout:15000,response:{response:{responseFormat:'json'}}}}},
 {id:'screen',name:'Flag evidence quality',type:'n8n-nodes-base.code',typeVersion:2,position:[500,40],parameters:{jsCode:"const factors = ['market_quality','liquidity_health','arbitrage_potential','order_flow','volatility','news_sentiment']; return $input.all().flatMap(item => (item.json.data || []).map(r => ({json: {...r, passes_screen: typeof r.score === 'number' && r.score >= 60 && typeof r.coverage === 'number' && r.coverage >= 0.8 && r.freshness === 'fresh' && factors.every(name => typeof r.factors?.[name]?.score === 'number' && r.factors[name].freshness === 'fresh'), screen_rule: 'score >= 60; coverage >= 0.8; all six factors present and fresh'}})));"}}
],connections:{'Run screen':{main:[[{node:'Fetch Vi IQ',type:'main',index:0}]]},'Fetch Vi IQ':{main:[[{node:'Flag evidence quality',type:'main',index:0}]]}},active:false,settings:{executionOrder:'v1'},pinData:{},tags:[]};
workflow.nodes.find(n => n.id === 'fetch').parameters.url = spec.servers[0].url.replace(/\/$/, '') + '/v1/iq';
await put('integrations/n8n/vi-iq-screen.json',workflow);
console.log('Generated OpenAPI, RapidAPI plans, Postman collection/environment and n8n workflow.');
